/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminLendersRouteImport } from './routes/admin/lenders'
import { Route as LenderClientsRouteImport } from './routes/lender/clients'
import { Route as LenderDashboardRouteImport } from './routes/lender/dashboard'
import { Route as LenderLoansRouteImport } from './routes/lender/loans'
import { Route as LenderReportsRouteImport } from './routes/lender/reports'
import { Route as LenderLoansIndexRouteImport } from './routes/lender/loans/index'
import { Route as LenderLoansClientIdRouteImport } from './routes/lender/loans/$clientId'
import { Route as LenderLoansPendingTodayRouteImport } from './routes/lender/loans/pending-today'
import { Route as LenderLoansClientIdIndexRouteImport } from './routes/lender/loans/$clientId/index'
import { Route as LenderLoansClientIdLoanIdRouteImport } from './routes/lender/loans/$clientId.$loanId'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLendersRoute = AdminLendersRouteImport.update({
  id: '/admin/lenders',
  path: '/admin/lenders',
  getParentRoute: () => rootRouteImport,
} as any)
const LenderClientsRoute = LenderClientsRouteImport.update({
  id: '/lender/clients',
  path: '/lender/clients',
  getParentRoute: () => rootRouteImport,
} as any)
const LenderDashboardRoute = LenderDashboardRouteImport.update({
  id: '/lender/dashboard',
  path: '/lender/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LenderLoansRoute = LenderLoansRouteImport.update({
  id: '/lender/loans',
  path: '/lender/loans',
  getParentRoute: () => rootRouteImport,
} as any)
const LenderReportsRoute = LenderReportsRouteImport.update({
  id: '/lender/reports',
  path: '/lender/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const LenderLoansIndexRoute = LenderLoansIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LenderLoansRoute,
} as any)
const LenderLoansClientIdRoute = LenderLoansClientIdRouteImport.update({
  id: '/$clientId',
  path: '/$clientId',
  getParentRoute: () => LenderLoansRoute,
} as any)
const LenderLoansPendingTodayRoute = LenderLoansPendingTodayRouteImport.update({
  id: '/pending-today',
  path: '/pending-today',
  getParentRoute: () => LenderLoansRoute,
} as any)
const LenderLoansClientIdIndexRoute =
  LenderLoansClientIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => LenderLoansClientIdRoute,
  } as any)
const LenderLoansClientIdLoanIdRoute =
  LenderLoansClientIdLoanIdRouteImport.update({
    id: '/$loanId',
    path: '/$loanId',
    getParentRoute: () => LenderLoansClientIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/auth': typeof AuthRoute
  '/admin/lenders': typeof AdminLendersRoute
  '/lender/clients': typeof LenderClientsRoute
  '/lender/dashboard': typeof LenderDashboardRoute
  '/lender/loans': typeof LenderLoansRouteWithChildren
  '/lender/reports': typeof LenderReportsRoute
  '/lender/loans/$clientId': typeof LenderLoansClientIdRouteWithChildren
  '/lender/loans/pending-today': typeof LenderLoansPendingTodayRoute
  '/lender/loans/': typeof LenderLoansIndexRoute
  '/lender/loans/$clientId/$loanId': typeof LenderLoansClientIdLoanIdRoute
  '/lender/loans/$clientId/': typeof LenderLoansClientIdIndexRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/admin/lenders': typeof AdminLendersRoute
  '/lender/clients': typeof LenderClientsRoute
  '/lender/dashboard': typeof LenderDashboardRoute
  '/lender/reports': typeof LenderReportsRoute
  '/lender/loans/pending-today': typeof LenderLoansPendingTodayRoute
  '/lender/loans': typeof LenderLoansIndexRoute
  '/lender/loans/$clientId/$loanId': typeof LenderLoansClientIdLoanIdRoute
  '/lender/loans/$clientId': typeof LenderLoansClientIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/auth': typeof AuthRoute
  '/admin/lenders': typeof AdminLendersRoute
  '/lender/clients': typeof LenderClientsRoute
  '/lender/dashboard': typeof LenderDashboardRoute
  '/lender/loans': typeof LenderLoansRouteWithChildren
  '/lender/reports': typeof LenderReportsRoute
  '/lender/loans/$clientId': typeof LenderLoansClientIdRouteWithChildren
  '/lender/loans/pending-today': typeof LenderLoansPendingTodayRoute
  '/lender/loans/': typeof LenderLoansIndexRoute
  '/lender/loans/$clientId/$loanId': typeof LenderLoansClientIdLoanIdRoute
  '/lender/loans/$clientId/': typeof LenderLoansClientIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/auth'
    | '/admin/lenders'
    | '/lender/clients'
    | '/lender/dashboard'
    | '/lender/loans'
    | '/lender/reports'
    | '/lender/loans/$clientId'
    | '/lender/loans/pending-today'
    | '/lender/loans/'
    | '/lender/loans/$clientId/$loanId'
    | '/lender/loans/$clientId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/admin/lenders'
    | '/lender/clients'
    | '/lender/dashboard'
    | '/lender/reports'
    | '/lender/loans/pending-today'
    | '/lender/loans'
    | '/lender/loans/$clientId/$loanId'
    | '/lender/loans/$clientId'
  id:
    | '__root__'
    | '/auth'
    | '/admin/lenders'
    | '/lender/clients'
    | '/lender/dashboard'
    | '/lender/loans'
    | '/lender/reports'
    | '/lender/loans/$clientId'
    | '/lender/loans/pending-today'
    | '/lender/loans/'
    | '/lender/loans/$clientId/$loanId'
    | '/lender/loans/$clientId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRoute
  AdminLendersRoute: typeof AdminLendersRoute
  LenderClientsRoute: typeof LenderClientsRoute
  LenderDashboardRoute: typeof LenderDashboardRoute
  LenderLoansRoute: typeof LenderLoansRouteWithChildren
  LenderReportsRoute: typeof LenderReportsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/lenders': {
      id: '/admin/lenders'
      path: '/admin/lenders'
      fullPath: '/admin/lenders'
      preLoaderRoute: typeof AdminLendersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lender/clients': {
      id: '/lender/clients'
      path: '/lender/clients'
      fullPath: '/lender/clients'
      preLoaderRoute: typeof LenderClientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lender/dashboard': {
      id: '/lender/dashboard'
      path: '/lender/dashboard'
      fullPath: '/lender/dashboard'
      preLoaderRoute: typeof LenderDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lender/loans': {
      id: '/lender/loans'
      path: '/lender/loans'
      fullPath: '/lender/loans'
      preLoaderRoute: typeof LenderLoansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lender/reports': {
      id: '/lender/reports'
      path: '/lender/reports'
      fullPath: '/lender/reports'
      preLoaderRoute: typeof LenderReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lender/loans/': {
      id: '/lender/loans/'
      path: '/'
      fullPath: '/lender/loans/'
      preLoaderRoute: typeof LenderLoansIndexRouteImport
      parentRoute: typeof LenderLoansRoute
    }
    '/lender/loans/$clientId': {
      id: '/lender/loans/$clientId'
      path: '/$clientId'
      fullPath: '/lender/loans/$clientId'
      preLoaderRoute: typeof LenderLoansClientIdRouteImport
      parentRoute: typeof LenderLoansRoute
    }
    '/lender/loans/pending-today': {
      id: '/lender/loans/pending-today'
      path: '/pending-today'
      fullPath: '/lender/loans/pending-today'
      preLoaderRoute: typeof LenderLoansPendingTodayRouteImport
      parentRoute: typeof LenderLoansRoute
    }
    '/lender/loans/$clientId/': {
      id: '/lender/loans/$clientId/'
      path: '/'
      fullPath: '/lender/loans/$clientId/'
      preLoaderRoute: typeof LenderLoansClientIdIndexRouteImport
      parentRoute: typeof LenderLoansClientIdRoute
    }
    '/lender/loans/$clientId/$loanId': {
      id: '/lender/loans/$clientId/$loanId'
      path: '/$loanId'
      fullPath: '/lender/loans/$clientId/$loanId'
      preLoaderRoute: typeof LenderLoansClientIdLoanIdRouteImport
      parentRoute: typeof LenderLoansClientIdRoute
    }
  }
}

interface LenderLoansClientIdRouteChildren {
  LenderLoansClientIdLoanIdRoute: typeof LenderLoansClientIdLoanIdRoute
  LenderLoansClientIdIndexRoute: typeof LenderLoansClientIdIndexRoute
}

const LenderLoansClientIdRouteChildren: LenderLoansClientIdRouteChildren = {
  LenderLoansClientIdLoanIdRoute: LenderLoansClientIdLoanIdRoute,
  LenderLoansClientIdIndexRoute: LenderLoansClientIdIndexRoute,
}

const LenderLoansClientIdRouteWithChildren =
  LenderLoansClientIdRoute._addFileChildren(LenderLoansClientIdRouteChildren)

interface LenderLoansRouteChildren {
  LenderLoansClientIdRoute: typeof LenderLoansClientIdRouteWithChildren
  LenderLoansPendingTodayRoute: typeof LenderLoansPendingTodayRoute
  LenderLoansIndexRoute: typeof LenderLoansIndexRoute
}

const LenderLoansRouteChildren: LenderLoansRouteChildren = {
  LenderLoansClientIdRoute: LenderLoansClientIdRouteWithChildren,
  LenderLoansPendingTodayRoute: LenderLoansPendingTodayRoute,
  LenderLoansIndexRoute: LenderLoansIndexRoute,
}

const LenderLoansRouteWithChildren = LenderLoansRoute._addFileChildren(
  LenderLoansRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRoute,
  AdminLendersRoute: AdminLendersRoute,
  LenderClientsRoute: LenderClientsRoute,
  LenderDashboardRoute: LenderDashboardRoute,
  LenderLoansRoute: LenderLoansRouteWithChildren,
  LenderReportsRoute: LenderReportsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
