/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminLendersRouteImport } from './routes/admin/lenders'
import { Route as LenderDashboardRouteImport } from './routes/lender/dashboard'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLendersRoute = AdminLendersRouteImport.update({
  id: '/admin/lenders',
  path: '/admin/lenders',
  getParentRoute: () => rootRouteImport,
} as any)
const LenderDashboardRoute = LenderDashboardRouteImport.update({
  id: '/lender/dashboard',
  path: '/lender/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/auth': typeof AuthRoute
  '/admin/lenders': typeof AdminLendersRoute
  '/lender/dashboard': typeof LenderDashboardRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/admin/lenders': typeof AdminLendersRoute
  '/lender/dashboard': typeof LenderDashboardRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/auth': typeof AuthRoute
  '/admin/lenders': typeof AdminLendersRoute
  '/lender/dashboard': typeof LenderDashboardRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/auth' | '/admin/lenders' | '/lender/dashboard'
  fileRoutesByTo: FileRoutesByTo
  to: '/auth' | '/admin/lenders' | '/lender/dashboard'
  id: '__root__' | '/auth' | '/admin/lenders' | '/lender/dashboard'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRoute
  AdminLendersRoute: typeof AdminLendersRoute
  LenderDashboardRoute: typeof LenderDashboardRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/lenders': {
      id: '/admin/lenders'
      path: '/admin/lenders'
      fullPath: '/admin/lenders'
      preLoaderRoute: typeof AdminLendersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lender/dashboard': {
      id: '/lender/dashboard'
      path: '/lender/dashboard'
      fullPath: '/lender/dashboard'
      preLoaderRoute: typeof LenderDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRoute,
  AdminLendersRoute: AdminLendersRoute,
  LenderDashboardRoute: LenderDashboardRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
